[package]
name = "coordinated_rayon"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon-core = "1"
zmq = "0.10"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
log = "0.4"
anyhow = "1"

[dev-dependencies]
rayon = "1.10.0"
env_logger = "0.11.3"